CREATE TABLE dim_customer (
    customer_key   NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_dim_customer PRIMARY KEY, -- surrogate key
    customer_id    VARCHAR2(30),         -- ID ze źródła (np. SKLEP INTERNETOWY, SKLEP STACJONARNY, SYSTEM ERP )
    customer_name  VARCHAR2(100),        -- imię i nazwisko
    segment        VARCHAR2(50),         -- np. RETAIL / BUSINESS / VIP / INTERNAL / ONLINE / OFFLINE
    created_at     DATE DEFAULT SYSDATE  -- kiedy dodaliśmy klienta do wymiaru
);

