CREATE TABLE dim_product (
    product_key   NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_dim_product PRIMARY KEY, -- surrogate key 
    product_id    VARCHAR2(30),      -- ID ze źródła
    product_name  VARCHAR2(100),     
    category      VARCHAR2(50),      -- kategoria produktu
    created_at    DATE DEFAULT SYSDATE
);

