CREATE TABLE fact_sales (
    fact_id       NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_fact_sales PRIMARY KEY, 
    customer_key  NUMBER, --klucz obcy  tabeli dim_customer
    product_key   NUMBER, --klucz obcy tabel dim_product
    date_key      NUMBER, --klucz obcy  tabeli dim_date
    quantity      NUMBER,
    amount        NUMBER,
    load_ts       DATE DEFAULT SYSDATE
);
