CREATE TABLE ETL_LOG (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id NUMBER,
    process_name VARCHAR2(100), --nazwa procesu np ETL_SALES
    procedure_name VARCHAR2(100), -- Nazwa procedury
    start_ts TIMESTAMP, --czas rozpoczęcia
    end_ts TIMESTAMP, --czas zakończenia 
    status VARCHAR(20) CHECK (status in ('STARTED', 'SUCCESS', 'WARNING', 'FAILED')), -- STARTED / SUCCESS / WARNING / FAILED

    rows_read NUMBER, --Liczba wczytanych rekordów
    rows_inserted NUMBER,-- liczba wstawionych rekordow
    rows_rejected NUMBER, -- liczba rekordow odrzuconych 
    message VARCHAR2(4000),
    created_at DATE DEFAULT SYSDATE -- data utworzenia logu 
);

CREATE TABLE ETL_ERROR_LOG(
    error_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id NUMBER,
    procedure_name VARCHAR(100),
    table_name VARCHAR(50), --docelowa tabela
    source_table VARCHAR(50), --tabela źródłowa
    record_id VARCHAR2(100), -- id rekordu źródłowego np. src_sale_id
    error_type VARCHAR2(50), --typ błedu
    error_message VARCHAR2(4000),
    error_ts TIMESTAMP DEFAULT SYSTIMESTAMP, -- czas wystepienia błedu
    column_name VARCHAR2(50), --kolumna powodujaca bład
    invalid_value VARCHAR2(4000), -- niepoprawna wartosc
    created_at DATE DEFAULT SYSDATE -- data wpisu
);