CREATE TABLE t_log_file (
    log_file_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    load_id        NUMBER,
    process_name   VARCHAR2(100),
    procedure_name VARCHAR2(100),
    log_type       VARCHAR2(20),
    directory_name VARCHAR2(100),
    file_name      VARCHAR2(255),
    status         VARCHAR2(20),
    message_count  NUMBER DEFAULT 0,
    created_at     DATE DEFAULT SYSDATE,
    closed_at      DATE
);


ALTER TABLE t_log_file
ADD CONSTRAINT pk_t_log_file PRIMARY KEY (log_file_id);

ALTER TABLE t_log_file
ADD CONSTRAINT ck_t_log_file_type CHECK (log_type IN ('DEBUG','ERROR'));

ALTER TABLE t_log_file
ADD CONSTRAINT ck_t_log_file_status CHECK (status IN ('CREATED','WRITTEN','FAILED'));
