CREATE TABLE t_params (
    param_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    param_name   VARCHAR2(100),
    param_value  VARCHAR2(4000),
    param_desc   VARCHAR2(500),
    is_active    CHAR(1) DEFAULT 'Y',
    created_at   DATE DEFAULT SYSDATE,
    updated_at   DATE
);

ALTER TABLE t_params
ADD CONSTRAINT pk_t_params PRIMARY KEY (param_id);

ALTER TABLE t_params
ADD CONSTRAINT uk_t_params_name UNIQUE (param_name);

ALTER TABLE t_params
ADD CONSTRAINT ck_t_params_active CHECK (is_active IN ('Y','N'));